name: nursa
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  timezone: ^0.9.2
  flutter_local_notifications: ^14.1.1
  alarm: ^1.1.4
  get: ^4.6.5
  cloud_firestore: ^4.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/
   
 